// src/lib/components/TrendsSection.svelte
<script lang="ts">
	import Sparkline from '$lib/components/Sparkline.svelte';
	import type { TrainingTrends, TrendSeries } from '$lib/trends';

	type Props = {
		trends: TrainingTrends;
		/** Optional heading override (e.g. when a date range is active). */
		heading?: string;
		caption?: string;
	};

	let {
		trends,
		heading = 'Trends',
		caption = 'Progress over recent weeks and runs'
	}: Props = $props();

	let activeBar = $state<number | null>(null);
	let barPinned = $state(false);
	let barChartEl: HTMLDivElement | undefined = $state();

	function maxBar(series: TrendSeries): number {
		return Math.max(...series.points.map((p) => p.value), 0.1);
	}

	function barHeight(value: number, max: number): string {
		const pct = Math.max(4, Math.round((value / max) * 100));
		return `${pct}%`;
	}

	function showBar(i: number) {
		activeBar = i;
	}

	function clearBarIfUnpinned() {
		if (!barPinned) activeBar = null;
	}

	function onBarEnter(i: number) {
		if (!barPinned) showBar(i);
	}

	function onBarLeave() {
		clearBarIfUnpinned();
	}

	function onBarClick(i: number, e: MouseEvent) {
		e.stopPropagation();
		// Fine pointers already get hover tooltips; tap/pin is for touch.
		if (typeof window !== 'undefined' && window.matchMedia('(hover: hover) and (pointer: fine)').matches) {
			showBar(i);
			return;
		}
		if (barPinned && activeBar === i) {
			barPinned = false;
			activeBar = null;
			return;
		}
		barPinned = true;
		activeBar = i;
	}

	function onDocPointerDown(e: PointerEvent) {
		if (!barPinned || !barChartEl) return;
		if (e.target instanceof Node && barChartEl.contains(e.target)) return;
		barPinned = false;
		activeBar = null;
	}

	$effect(() => {
		if (!barPinned) return;
		document.addEventListener('pointerdown', onDocPointerDown);
		return () => document.removeEventListener('pointerdown', onDocPointerDown);
	});
</script>

{#if trends.series.length}
	<section class="trends" aria-labelledby="trends-heading">
		<div class="trends-head">
			<h2 id="trends-heading">{heading}</h2>
			<p class="muted">{caption}</p>
		</div>

		<div class="trends-grid">
			{#each trends.series as series (series.id)}
				<article class="trend-item" class:trend-bars={series.bars}>
					<header class="trend-meta">
						<div>
							<span class="trend-title">{series.title}</span>
							<span class="trend-sub muted">{series.subtitle}</span>
						</div>
						<div class="trend-readout" aria-label={`${series.title} latest`}>
							{#if series.latest}
								<strong
									>{series.latest}<span class="trend-unit">{series.unit}</span></strong
								>
							{/if}
							{#if series.delta}
								<span
									class="trend-delta"
									class:better={series.delta.startsWith('↓') && series.lowerIsBetter}
									class:worse={series.delta.startsWith('↑') && series.lowerIsBetter}
									class:up={series.delta.startsWith('↑') && !series.lowerIsBetter}
									>{series.delta}</span
								>
							{/if}
						</div>
					</header>

					{#if series.bars}
						{@const max = maxBar(series)}
						<div
							class="bar-chart"
							bind:this={barChartEl}
							role="group"
							aria-label={`${series.title}: ${series.points.map((p) => p.display).join(', ')}`}
						>
							{#each series.points as point, i}
								<button
									type="button"
									class="bar-col"
									class:active={activeBar === i}
									aria-label={`${point.label}: ${point.display}`}
									onpointerenter={() => onBarEnter(i)}
									onpointerleave={onBarLeave}
									onclick={(e) => onBarClick(i, e)}
								>
									<div class="bar-track">
										<span
											class="bar"
											class:empty={point.value <= 0}
											style={`height:${barHeight(point.value, max)}`}
										></span>
									</div>
									<span class="bar-label muted">{point.label}</span>
									{#if activeBar === i}
										<span class="bar-tip" role="tooltip">
											<span class="bar-tip-value">{point.display}</span>
											<span class="bar-tip-label">{point.label}</span>
										</span>
									{/if}
								</button>
							{/each}
						</div>
					{:else}
						<div class="spark-wrap">
							<Sparkline
								values={series.points.map((p) => p.value)}
								tips={series.points.map((p) => ({
									label: p.label,
									display: p.display
								}))}
								label={`${series.title}: ${series.points.map((p) => p.display).join(', ')}`}
								height={44}
							/>
							<div class="spark-ends muted" aria-hidden="true">
								<span>{series.points[0]?.label}</span>
								<span>{series.points[series.points.length - 1]?.label}</span>
							</div>
						</div>
					{/if}
				</article>
			{/each}
		</div>
	</section>
{/if}

<style>
	.trends {
		margin: 0 0 1.75rem;
		padding: 1.1rem 0 0.15rem;
		border-top: 1px solid var(--line);
	}

	.trends-head {
		margin-bottom: 0.95rem;
	}

	.trends-head h2 {
		font-size: 1.2rem;
		font-weight: 700;
	}

	.trends-head p {
		margin-top: 0.25rem;
		font-size: 0.9rem;
	}

	.trends-grid {
		display: grid;
		grid-template-columns: repeat(2, minmax(0, 1fr));
		gap: 1.15rem 1.5rem;
	}

	.trend-item.trend-bars {
		grid-column: 1 / -1;
	}

	.trend-meta {
		display: flex;
		align-items: flex-start;
		justify-content: space-between;
		gap: 0.75rem;
		margin-bottom: 0.55rem;
	}

	.trend-title {
		display: block;
		font-family: var(--font-display);
		font-weight: 700;
		letter-spacing: -0.02em;
		font-size: 0.98rem;
	}

	.trend-sub {
		display: block;
		font-size: 0.78rem;
		margin-top: 0.15rem;
	}

	.trend-readout {
		text-align: right;
		flex-shrink: 0;
	}

	.trend-readout strong {
		display: block;
		font-family: var(--font-display);
		font-size: 1.15rem;
		letter-spacing: -0.03em;
		line-height: 1.1;
	}

	.trend-unit {
		font-size: 0.75rem;
		font-weight: 500;
		color: var(--muted);
		margin-left: 0.15rem;
	}

	.trend-delta {
		display: inline-block;
		margin-top: 0.15rem;
		font-size: 0.78rem;
		color: var(--muted);
	}

	.trend-delta.better,
	.trend-delta.up {
		color: var(--ok);
	}

	.trend-delta.worse {
		color: var(--warn);
	}

	.spark-wrap {
		min-width: 0;
		overflow: visible;
		padding-top: 1.85rem;
		margin-top: -1.85rem;
	}

	.spark-ends {
		display: flex;
		justify-content: space-between;
		font-size: 0.72rem;
		margin-top: 0.2rem;
	}

	.bar-chart {
		display: flex;
		align-items: stretch;
		gap: 0.28rem;
		height: 4.6rem;
		min-width: 0;
		overflow: visible;
		padding-top: 1.85rem;
		margin-top: -1.85rem;
	}

	.bar-col {
		position: relative;
		flex: 1 1 0;
		min-width: 0;
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 0.28rem;
		padding: 0;
		margin: 0;
		border: 0;
		background: transparent;
		color: inherit;
		font: inherit;
		cursor: pointer;
		touch-action: manipulation;
		-webkit-tap-highlight-color: transparent;
	}

	.bar-track {
		flex: 1;
		width: 100%;
		display: flex;
		align-items: flex-end;
		justify-content: center;
	}

	.bar {
		display: block;
		width: 100%;
		max-width: 1.35rem;
		border-radius: 3px 3px 1px 1px;
		background: linear-gradient(180deg, var(--accent) 0%, rgba(200, 242, 90, 0.45) 100%);
		min-height: 3px;
		transition: filter 0.12s ease, opacity 0.12s ease;
	}

	.bar-col.active .bar:not(.empty),
	.bar-col:hover .bar:not(.empty) {
		filter: brightness(1.08);
	}

	.bar.empty {
		opacity: 0.22;
		background: var(--line);
		min-height: 2px;
		height: 4% !important;
	}

	.bar-label {
		font-size: 0.62rem;
		line-height: 1.1;
		text-align: center;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		max-width: 100%;
	}

	.bar-tip {
		position: absolute;
		z-index: 3;
		bottom: calc(100% - 0.1rem);
		left: 50%;
		transform: translateX(-50%);
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 0.05rem;
		padding: 0.28rem 0.45rem;
		border-radius: 8px;
		border: 1px solid var(--line);
		background: #1a2218;
		box-shadow: 0 8px 22px rgba(0, 0, 0, 0.4);
		pointer-events: none;
		white-space: nowrap;
	}

	.bar-tip::after {
		content: '';
		position: absolute;
		top: 100%;
		left: 50%;
		transform: translateX(-50%);
		border: 5px solid transparent;
		border-top-color: #1a2218;
	}

	.bar-tip-value {
		font-family: var(--font-display);
		font-weight: 700;
		font-size: 0.78rem;
		letter-spacing: -0.02em;
		color: var(--accent);
		line-height: 1.15;
	}

	.bar-tip-label {
		font-size: 0.68rem;
		color: var(--muted);
		line-height: 1.15;
	}

	@media (max-width: 720px) {
		.trends-grid {
			grid-template-columns: 1fr;
			gap: 1.25rem;
		}

		.bar-chart {
			height: 4.2rem;
			gap: 0.18rem;
		}

		.bar-label {
			font-size: 0.58rem;
		}

		/* Hide every other week label on narrow screens to reduce clutter */
		.bar-col:nth-child(even) .bar-label {
			visibility: hidden;
		}
	}
</style>

// src/components/TrendsSection.tsx
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { Sparkline } from './Sparkline';
import type { TrainingTrends, TrendSeries } from '$lib/trends';
import { cn, ui } from '$lib/ui';

type Props = {
	trends: TrainingTrends;
	heading?: string;
	caption?: string;
};

export function TrendsSection({
	trends,
	heading = 'Trends',
	caption = 'Progress over recent weeks'
}: Props) {
	const [activeBar, setActiveBar] = useState<number | null>(null);
	const [barPinned, setBarPinned] = useState(false);
	const barChartRef = useRef<HTMLDivElement>(null);
	const navigate = useNavigate();

	function maxBar(series: TrendSeries): number {
		return Math.max(...series.points.map((p) => p.value), 0.1);
	}

	function barHeight(value: number, max: number): string {
		const pct = Math.max(4, Math.round((value / max) * 100));
		return `${pct}%`;
	}

	function onBarEnter(i: number) {
		if (!barPinned) setActiveBar(i);
	}

	function onBarLeave() {
		if (!barPinned) setActiveBar(null);
	}

	function onBarClick(i: number, e: React.MouseEvent) {
		e.stopPropagation();
		if (
			typeof window !== 'undefined' &&
			window.matchMedia('(hover: hover) and (pointer: fine)').matches
		) {
			setActiveBar(i);
			return;
		}
		if (barPinned && activeBar === i) {
			setBarPinned(false);
			setActiveBar(null);
			return;
		}
		setBarPinned(true);
		setActiveBar(i);
	}

	useEffect(() => {
		if (!barPinned) return;
		function onDocPointerDown(e: PointerEvent) {
			if (!barChartRef.current) return;
			if (e.target instanceof Node && barChartRef.current.contains(e.target)) return;
			setBarPinned(false);
			setActiveBar(null);
		}
		document.addEventListener('pointerdown', onDocPointerDown);
		return () => document.removeEventListener('pointerdown', onDocPointerDown);
	}, [barPinned]);

	if (!trends.series.length) return null;

	return (
		<section className="mt-[1.4rem] mb-[1.75rem] p-0" aria-labelledby="trends-heading">
			<div className="mb-[1.1rem]">
				<h2 id="trends-heading" className="text-[1.5rem] font-extrabold tracking-[-0.02em]">
					{heading}
				</h2>
				<p className={cn(ui.muted, 'mt-[0.2rem] text-[0.9rem]')}>{caption}</p>
			</div>

			<div className="grid grid-cols-1 gap-x-6 gap-y-[1.15rem] min-[721px]:grid-cols-2 max-[720px]:gap-5">
				{trends.series.map((series) => {
					const max = maxBar(series);
					return (
						<article key={series.id} className={series.bars ? 'col-span-full' : undefined}>
							<header className="flex items-start justify-between gap-3 mb-[0.55rem]">
								<div>
									<span className="block font-semibold uppercase tracking-[0.06em] text-[0.78rem] text-muted">
										{series.title}
									</span>
									<span className={cn(ui.muted, 'block text-[0.78rem] mt-[0.15rem]')}>
										{series.subtitle}
									</span>
								</div>
								<div className="text-right shrink-0" aria-label={`${series.title} latest`}>
									{series.latest && (
										<strong className="block font-display text-[1.15rem] tracking-[-0.03em] leading-[1.1]">
											{series.latest}
											<span className="text-[0.75rem] font-medium text-muted ml-[0.15rem]">
												{series.unit}
											</span>
										</strong>
									)}
									{series.delta && (
										<span
											className={cn(
												'inline-block mt-[0.15rem] text-[0.78rem] text-muted',
												series.delta.startsWith('↓') && series.lowerIsBetter && 'text-ok',
												series.delta.startsWith('↑') && series.lowerIsBetter && 'text-warn',
												series.delta.startsWith('↑') && !series.lowerIsBetter && 'text-ok'
											)}
										>
											{series.delta}
										</span>
									)}
								</div>
							</header>

							{series.bars ? (
								<div
									className="flex items-stretch gap-[0.28rem] h-[4.6rem] min-w-0 overflow-visible pt-[1.85rem] -mt-[1.85rem] max-[720px]:h-[4.2rem] max-[720px]:gap-[0.18rem]"
									ref={barChartRef}
									role="group"
									aria-label={`${series.title}: ${series.points.map((p) => p.display).join(', ')}`}
								>
									{series.points.map((point, i) => (
										<button
											key={i}
											type="button"
											className="group/bar relative flex-1 min-w-0 flex flex-col items-center gap-[0.28rem] p-0 m-0 border-0 bg-transparent text-inherit font-inherit cursor-pointer touch-manipulation [-webkit-tap-highlight-color:transparent] max-[720px]:even:[&>span:first-of-type]:invisible"
											aria-label={`${point.label}: ${point.display}`}
											onPointerEnter={() => onBarEnter(i)}
											onPointerLeave={onBarLeave}
											onClick={(e) => onBarClick(i, e)}
										>
											<div className="flex-1 w-full flex items-end justify-center">
												<span
													className={cn(
														'block w-full max-w-[1.35rem] rounded-[3px_3px_1px_1px] bg-[linear-gradient(180deg,var(--color-accent)_0%,rgba(200,242,90,0.45)_100%)] min-h-[3px] transition-[filter,opacity] duration-100 group-hover/bar:brightness-[1.08] group-active/bar:brightness-[1.08]',
														point.value <= 0
															? 'opacity-[0.22] bg-line min-h-[2px] !h-[4%] group-hover/bar:brightness-100 group-active/bar:brightness-100'
															: activeBar === i
																? 'brightness-[1.08]'
																: ''
													)}
													style={{ height: barHeight(point.value, max) }}
												></span>
											</div>
											<span className="text-[0.62rem] leading-[1.1] text-center whitespace-nowrap overflow-hidden text-ellipsis max-w-full text-muted max-[720px]:text-[0.58rem]">
												{point.label}
											</span>
											{activeBar === i && (
												<span className="absolute z-[3] bottom-[calc(100%-0.1rem)] left-1/2 -translate-x-1/2 flex flex-col items-center gap-[0.05rem] px-[0.45rem] py-[0.28rem] rounded-lg border border-line bg-[#1a2218] shadow-[0_8px_22px_rgba(0,0,0,0.4)] pointer-events-none whitespace-nowrap after:content-[''] after:absolute after:top-full after:left-1/2 after:-translate-x-1/2 after:border-[5px] after:border-transparent after:border-t-[#1a2218]" role="tooltip">
													<span className="font-display font-bold text-[0.78rem] tracking-[-0.02em] text-accent leading-[1.15]">
														{point.display}
													</span>
													<span className="text-[0.68rem] text-muted leading-[1.15]">
														{point.label}
													</span>
												</span>
											)}
										</button>
									))}
								</div>
							) : (
								<div className="min-w-0 overflow-visible pt-[1.85rem] -mt-[1.85rem]">
									<Sparkline
										values={series.points.map((p) => p.value)}
										tips={series.points.map((p) => ({ label: p.label, display: p.display }))}
										label={`${series.title}: ${series.points.map((p) => p.display).join(', ')}`}
										height={44}
										onPick={
											series.points.some((p) => p.slug)
												? (i) => {
														const slug = series.points[i]?.slug;
														if (slug) navigate({ to: '/runs/$slug', params: { slug } });
													}
												: undefined
										}
									/>
									<div className="flex justify-between text-[0.72rem] mt-[0.2rem] text-muted" aria-hidden="true">
										<span>{series.points[0]?.label}</span>
										<span>{series.points[series.points.length - 1]?.label}</span>
									</div>
								</div>
							)}
						</article>
					);
				})}
			</div>
		</section>
	);
}
