// src/routes/context.tsx
import { useAuthed } from '$lib/auth';
import { getContextData, saveContextFile, saveShoes } from '$lib/server/functions';
import { cn, ui } from '$lib/ui';
import { createFileRoute, useRouter } from '@tanstack/react-router';
import { useState } from 'react';
import { DeferredData } from '../components/DeferredData';
import { errorMessage, useSnackbar } from '../components/Snackbar';

export const Route = createFileRoute('/context')({
	loader: () => ({ page: getContextData() }),
	component: Context
});

function Context() {
	const { page } = Route.useLoaderData();
	return (
		<>
			<section className={ui.hero}>
				<div>
					<p className={ui.muted}>Profile, gear, and race notes</p>
					<h1>Context</h1>
					<p>Read the formatted docs and edit markdown when something changes.</p>
				</div>
			</section>
			<DeferredData promise={page}>{(data) => <ContextBody data={data} />}</DeferredData>
		</>
	);
}

function ContextBody({ data }: { data: Awaited<ReturnType<typeof getContextData>> }) {
	const router = useRouter();
	const authed = useAuthed();
	const snack = useSnackbar();

	const [copied, setCopied] = useState<string | null>(null);
	const [editing, setEditing] = useState<string | null>(null);
	const [draft, setDraft] = useState('');
	const [openName, setOpenName] = useState<string | null>(null);

	async function copyText(text: string, id: string) {
		const value = (text ?? '').trim();
		if (!value) {
			snack.error('Nothing to copy — this file looks empty.');
			return;
		}
		try {
			await navigator.clipboard.writeText(value);
		} catch {
			const ta = document.createElement('textarea');
			ta.value = value;
			ta.style.position = 'fixed';
			ta.style.left = '-9999px';
			document.body.appendChild(ta);
			ta.select();
			document.execCommand('copy');
			ta.remove();
		}
		setCopied(id);
		setTimeout(() => setCopied((c) => (c === id ? null : c)), 1800);
	}

	function startEdit(name: string, body: string) {
		setEditing(name);
		setDraft(body);
		setOpenName(name);
	}

	async function onSaveShoes(e: React.FormEvent<HTMLFormElement>) {
		e.preventDefault();
		const fd = new FormData(e.currentTarget);
		const active = String(fd.get('active') ?? '').trim();
		const rotation = String(fd.get('rotation') ?? '')
			.split('\n')
			.map((s) => s.trim())
			.filter(Boolean);
		const notes = String(fd.get('notes') ?? '');
		try {
			await saveShoes({ data: { active, rotation, notes } });
			snack.success('Saved shoes.md');
			router.invalidate();
		} catch (err) {
			snack.error(errorMessage(err, 'Save failed'));
		}
	}

	async function onSaveFile(e: React.FormEvent<HTMLFormElement>, name: string) {
		e.preventDefault();
		try {
			await saveContextFile({ data: { name, body: draft } });
			setEditing(null);
			setDraft('');
			setOpenName(name);
			snack.success(`Saved ${name}`);
			router.invalidate();
		} catch (err) {
			snack.error(errorMessage(err, 'Save failed'));
		}
	}

	return (
		<>
			{authed ? (
			<form className={cn(ui.panel, ui.form, 'mb-5')} method="POST" onSubmit={onSaveShoes}>
				<h2>Current shoes</h2>
				<div className={cn(ui.formGrid, 'mt-[0.8rem]')}>
					<label className={ui.field}>
						<span>Active pair</span>
						<input name="active" defaultValue={data.shoes.active} required />
					</label>
					<label className={ui.field}>
						<span>Rotation (one per line)</span>
						<textarea name="rotation" rows={3} defaultValue={data.shoes.rotation.join('\n')} />
					</label>
				</div>
				<label className={ui.field}>
					<span>Notes</span>
					<textarea name="notes" rows={3} defaultValue={data.shoes.notes} />
				</label>
				<button className={ui.btnPrimary} type="submit">
					Update shoes
				</button>
			</form>
			) : (
				<div className={cn(ui.panel, 'mb-5')}>
					<h2>Current shoes</h2>
					<p className="mt-[0.8rem] mb-0">
						<strong>{data.shoes.active || '—'}</strong>
						{data.shoes.rotation.length ? ` · ${data.shoes.rotation.join(', ')}` : ''}
					</p>
					{data.shoes.notes ? <p className={cn(ui.muted, 'mt-2 mb-0')}>{data.shoes.notes}</p> : null}
				</div>
			)}

			<div className={ui.grid}>
				{data.files.map((file) => (
					<details
						key={file.name}
						id={`ctx-${file.name}`}
						className={ui.panel}
						open={openName === file.name || editing === file.name}
					>
						<summary className="cursor-pointer list-none flex flex-wrap items-baseline gap-x-3 gap-y-[0.45rem] min-h-11 [&::-webkit-details-marker]:hidden">
							<span className="font-display text-[1.15rem] max-sm:text-[1.05rem] max-sm:[overflow-wrap:anywhere]">
								{file.title}
							</span>
							<span className={cn(ui.muted, 'text-[0.85rem] max-sm:flex-[1_1_100%] max-sm:text-[0.8rem] max-sm:[overflow-wrap:anywhere] max-sm:break-words')}>
								data/context/{file.name}
							</span>
						</summary>

						<div className={cn(ui.actions, 'mt-[0.85rem]')}>
							<button
								className={ui.btnGhost}
								type="button"
								onClick={() => copyText(file.body, file.name)}
							>
								{copied === file.name ? 'Copied' : 'Copy'}
							</button>
							{authed && editing !== file.name && (
								<button
									className={ui.btnGhost}
									type="button"
									onClick={() => startEdit(file.name, file.body)}
								>
									Edit
								</button>
							)}
						</div>

						{editing === file.name ? (
							<form
								className={cn(ui.form, 'mt-[0.9rem]')}
								method="POST"
								onSubmit={(e) => onSaveFile(e, file.name)}
							>
								<label className={ui.field}>
									<span>Markdown source</span>
									<textarea
										name="body"
										className={ui.editor}
										rows={18}
										value={draft}
										onChange={(e) => setDraft(e.target.value)}
									/>
								</label>
								<div className={ui.actions}>
									<button className={ui.btnPrimary} type="submit">
										Save
									</button>
									<button className={ui.btnGhost} type="button" onClick={() => setEditing(null)}>
										Cancel
									</button>
								</div>
							</form>
						) : (
							<div className="md" dangerouslySetInnerHTML={{ __html: file.html }} />
						)}
					</details>
				))}
			</div>
		</>
	);
}

// src/routes/context/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { SubmitFunction } from '@sveltejs/kit';

	let { data, form } = $props();
	let copied = $state<string | null>(null);
	let copyError = $state('');
	let editing = $state<string | null>(null);
	let draft = $state('');
	let openName = $state<string | null>(null);
	let saveFlash = $state('');

	const files = $derived(data.files);

	async function copyText(text: string, id: string) {
		copyError = '';
		const value = (text ?? '').trim();
		if (!value) {
			copyError = 'Nothing to copy — this file looks empty.';
			return;
		}
		try {
			await navigator.clipboard.writeText(value);
		} catch {
			const ta = document.createElement('textarea');
			ta.value = value;
			ta.style.position = 'fixed';
			ta.style.left = '-9999px';
			document.body.appendChild(ta);
			ta.select();
			document.execCommand('copy');
			ta.remove();
		}
		copied = id;
		setTimeout(() => {
			if (copied === id) copied = null;
		}, 1800);
	}

	function startEdit(name: string, body: string) {
		editing = name;
		draft = body;
		openName = name;
		saveFlash = '';
	}

	function cancelEdit() {
		editing = null;
		draft = '';
	}

	const saveEnhance =
		(name: string): SubmitFunction =>
		() => {
			const y = window.scrollY;
			return async ({ result, update }) => {
				await update({ reset: false });
				if (result.type === 'success' && result.data && 'saved' in result.data) {
					editing = null;
					draft = '';
					openName = name;
					saveFlash = String(result.data.saved);
					requestAnimationFrame(() => {
						window.scrollTo(0, y);
						document.getElementById(`ctx-${CSS.escape(name)}`)?.scrollIntoView({
							block: 'nearest'
						});
						window.scrollTo(0, y);
					});
				}
			};
		};
</script>

<section class="hero">
	<div>
		<p class="muted">Profile, plan, gear, and race notes</p>
		<h1>Context</h1>
		<p>Read the formatted docs and edit markdown when something changes.</p>
	</div>
</section>

{#if copyError}
	<div class="flash">{copyError}</div>
{/if}
{#if saveFlash || form?.saved}
	<div class="flash ok-flash">Saved {saveFlash || form?.saved}</div>
{/if}
{#if form?.message}
	<div class="flash">{form.message}</div>
{/if}

<form class="panel form" method="POST" action="?/shoes" style="margin-bottom:1.25rem">
	<h2>Current shoes</h2>
	<div class="form-grid" style="margin-top:0.8rem">
		<label class="field">
			<span>Active pair</span>
			<input name="active" value={data.shoes.active} required />
		</label>
		<label class="field">
			<span>Rotation (one per line)</span>
			<textarea name="rotation" rows="3">{data.shoes.rotation.join('\n')}</textarea>
		</label>
	</div>
	<label class="field">
		<span>Notes</span>
		<textarea name="notes" rows="3">{data.shoes.notes}</textarea>
	</label>
	<button class="btn btn-primary" type="submit">Update shoes</button>
</form>

<div class="grid">
	{#each files as file}
		<details
			id="ctx-{file.name}"
			class="panel context-card"
			open={openName === file.name || editing === file.name}
		>
			<summary>
				<span class="context-title">{file.title}</span>
				<span class="muted context-path">data/context/{file.name}</span>
			</summary>

			<div class="actions" style="margin-top:0.85rem">
				<button
					class="btn btn-ghost"
					type="button"
					onclick={() => copyText(file.body, file.name)}
				>
					{copied === file.name ? 'Copied' : 'Copy'}
				</button>
				{#if editing !== file.name}
					<button
						class="btn btn-ghost"
						type="button"
						onclick={() => startEdit(file.name, file.body)}
					>
						Edit
					</button>
				{/if}
			</div>

			{#if editing === file.name}
				<form
					class="form"
					method="POST"
					action="?/saveFile"
					style="margin-top:0.9rem"
					use:enhance={saveEnhance(file.name)}
				>
					<input type="hidden" name="name" value={file.name} />
					<label class="field">
						<span>Markdown source</span>
						<textarea name="body" class="editor" rows="18" bind:value={draft}></textarea>
					</label>
					<div class="actions">
						<button class="btn btn-primary" type="submit">Save</button>
						<button class="btn btn-ghost" type="button" onclick={cancelEdit}>Cancel</button>
					</div>
				</form>
			{:else}
				<div class="md">{@html file.html}</div>
			{/if}
		</details>
	{/each}
</div>
